import type { Metadata } from "next";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "THUISA",
  description: "Generated by THUISA",
  icons: {
    icon: "/favicon.ico"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <Image src={`/android-chrome-512x512.png`} width={90} alt="THUISA Logo" height={90}></Image>
          <Link href={`/`}>Home</Link>
          <Link href={`/about`}>About</Link>
          <Link href={`/contact`}>Contact Us</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
