import { EventData } from "@/lib/types";

export const eventData: EventData[] = [
  {
    name: "yingxin 1",
    img: "yingxin1.JPG",
    day: undefined,
    month: "september",
    year: 2025,
    subInfo: "Freshmen Welcome Event",
    type: "Orientation / Community Bonding",
    who: "All new Indonesian freshmen at Tunghai University",
    location: "",
    about:
      "Yingxin 1 is the very first gathering of the semester, created to warmly welcome new Indonesian students. This orientation is your chance to meet fellow freshmen connect with seniors, and be introduced to Tunghai University and THUISA.",
    activities: [
      "Enjoy fun ice-breaking games",
      "interactive sessions",
      " group bonding designed to help you make friends and feel part of the community right away.",
    ],
    reasons: [
      "Instantly connect with fellow Indonesian students.",
      "Meet seniors who will guide and support you.",
      "Learn about campus life and opportunities.",
      "Build lasting friendships and memories.",
    ],
    note: "This is a mandatory event for all new Indonesian freshmen. No registration needed — just come, join, and enjoy!",
    noTicket: true,
  },
  {
    name: "yingxin 2",
    day: 13,
    month: "october",
    year: 2025,
    subInfo: "Trip & Bonding Adventure",
    type: "Student Trip / Bonding",
    who: "All Indonesian students at Tunghai",
    location: "",
    about:
      "Yingxin 2 is our follow-up event that takes you outside the classroom! This trip is all about bonding with fellow Indonesian students through fun activities in an exciting location.",
    activities: [
      "Group games & bonding sessions",
      "Exploring the destination (e.g., theme park, sightseeing)",
      "Team-building activities",
    ],
    reasons: [
      "Strengthen friendship with fellow Indonesians",
      "Experience fun outside campus",
      "Create unforgettable memories together",
    ],
    note: undefined,
  },
  {
    name: "halloween",
    day: 31,
    month: "october",
    year: 2025,
    subInfo: "Costume & Spooky Fun",
    type: "Holiday Celebration",
    who: "All Indonesian students at Tunghai",
    location: "Tunghai University Campus",
    about:
      "Celebrate the spooky season with THUISA! The Halloween event is filled with costumes, games, and themed activities that let students express creativity and enjoy a festive atmosphere together.",
    activities: [
      "Costume showcase",
      "Halloween-themed games",
      "Spooky snacks and fun",
    ],
    reasons: [
      "Enjoy a seasonal celebration",
      "Express your creativity",
      "Relax and have fun mid-semester",
    ],
    note: undefined,
  },
  {
    name: "christmas dinner",
    day: 24,
    month: "december",
    year: 2025,
    subInfo: "Warm & Joyful Gathering",
    type: "Holiday Dinner",
    who: "All Indonesian students at Tunghai",
    location: "Tunghai University",
    about:
      "A cozy Christmas celebration where Indonesian students gather to enjoy food, games, and festive vibes together. This event brings warmth during the holiday season, fostering a sense of family away from home.",
    activities: [
      "Christmas dinner",
      "Games and sharing",
      "Holiday celebration",
    ],
    reasons: [
      "Celebrate Christmas together",
      "Feel at home with your peers",
      "Build warm memories",
    ],
    note: undefined,
  },
  {
    name: "gala dinner",
    day: 15,
    month: "febuary",
    year: 2026,
    subInfo: "Cultural Exchange & Formal Celebration",
    type: "Formal Dinner / Cultural Showcase",
    who: "Indonesian & International students, OIR, and guests",
    location: "Tunghai University (Formal Hall)",
    about:
      "The Gala Dinner is a formal evening co-hosted with Tunghai’s OIR and other international student associations. It includes performances, cultural showcases, and networking opportunities while representing Indonesia with pride.",
    activities: [
      "Formal dinner",
      "Cultural performances",
      "Networking with international students",
    ],
    reasons: [
      "Represent Indonesia in a formal event",
      "Connect with OIR and other associations",
      "Celebrate diversity and culture",
    ],
    note: "Formal attire required.",
  },
  {
    name: "thuisa cup",
    day: 15,
    month: "march",
    year: 2026,
    subInfo: "Sports & Unity Challenge",
    type: "Sports Competition",
    who: "All Indonesian students in Taiwan",
    location: "Tunghai University",
    about:
      "A large-scale sports event that unites Indonesian students across Taiwan. The THUISA Cup allows participants to compete, build sportsmanship, and create connections beyond their own campus.",
    activities: [
      "Sports tournaments",
      "Team competitions",
      "Bonding with Indonesian students across Taiwan",
    ],
    reasons: [
      "Show your skills in sports",
      "Strengthen unity among Indonesians",
      "Connect beyond your own university",
    ],
    note: undefined,
  },
  {
    name: "international week",
    day: 20,
    month: "april",
    year: 2026,
    subInfo: "Culture & Flavors Festival",
    type: "Cultural Event",
    who: "Open to all Tunghai students and faculty",
    location: "Tunghai University",
    about:
      "A week-long cultural festival hosted by OIR where THUISA represents Indonesia. Students prepare booths with Indonesian food and traditions, sharing culture with the wider Tunghai community.",
    activities: [
      "Indonesian food booth",
      "Cultural display",
      "Cross-cultural exchange",
    ],
    reasons: [
      "Promote Indonesian culture",
      "Be part of a global event",
      "Celebrate diversity together",
    ],
    note: undefined,
    noTicket: true,
  },
  {
    name: "graduation",
    day: 15,
    month: "june",
    year: 2026,
    subInfo: "Honoring Our Seniors",
    type: "Graduation Ceremony",
    who: "Graduating Indonesian students, families, and friends",
    location: "Tunghai University (Organized by OIR)",
    about:
      "The graduation ceremony is the closing chapter of the academic journey. THUISA contributes to OIR’s official event to celebrate the achievements of graduating seniors, honoring their hard work and success.",
    activities: [
      "Graduation ceremony",
      "Celebration with peers and families",
      "Farewell to seniors",
    ],
    reasons: [
      "Celebrate achievements of seniors",
      "Support fellow Indonesians",
      "Mark a new beginning",
    ],
    note: undefined,
  },
];
